[package]
name = "common"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

rgb = "0.8.37"
anyhow = "1.0.86"
smart-leds-trait = "0.3.0"
either = "1.6.1"
